#!/usr/bin/env python3
"""Generate a derived file from the one definition, and refuse drift.

The METHOD §4 pattern, as a working skeleton. Copy it, replace `DEFINITION`
and `render()`, wire `--check` into your build.

WHY A GENERATOR AND NOT A CONVENTION. A fact written in two places drifts, and
the drift is a wrong answer rather than a crash. Measured instances: a test
runner kept its stage names in three places and two copies drifted, so two
stages ran without appearing in `--list` and one line claimed 15 sub-targets
after the real count had grown to 17. Separately, assigning one new opcode
number touched ten hand-written lists across four languages, and every single
one surfaced as a run-time refusal rather than at review.

WHY `--check` AND NOT JUST `--write`. A generator nobody runs is a second
copy with extra steps. `--check` belongs in the build, as a prerequisite of
something people already run, so the build fails when the committed file is
not what the definition produces. The generator is then the only way to change
the derived file, which is the property you want.

    python check_generated.py --write    # regenerate, for when you change the definition
    python check_generated.py --check    # fail if the committed file has drifted

EXIT CODES
    0  the committed file is exactly what the definition renders
    1  drift (with a diff), or the file is missing
    2  misuse
"""
import argparse
import difflib
import pathlib
import sys

# ---------------------------------------------------------------------------
# THE ONE DEFINITION. This is the only place these facts are written. Replace
# it with yours - a dict, a list of tuples, whatever the domain wants - and
# keep it in the module that owns the concept rather than in this script, so
# the runtime code imports the same object the generator renders.
# ---------------------------------------------------------------------------
DEFINITION = [
    # (bit, name, one-line meaning)
    (0, "INEXACT", "the result was rounded"),
    (1, "UNDERFLOW", "the result is subnormal or zero after rounding"),
    (2, "OVERFLOW", "the magnitude exceeded the format's range"),
    (3, "DIVBYZERO", "an exact infinity from finite operands"),
    (4, "INVALID", "no useful answer exists; the result is a quiet NaN"),
]

OUTPUT = pathlib.Path("generated_flags.h")

BANNER = "/* GENERATED by templates/check_generated.py - do not edit. */\n"


def render(definition):
    """-> the exact text the committed file must contain.

    Deterministic: same input, same bytes, every time. No timestamps, no
    absolute paths, no dict iteration order you have not fixed - a generator
    whose output wobbles makes `--check` useless and teaches people to pass
    --write to shut it up.
    """
    lines = [BANNER, "#ifndef GENERATED_FLAGS_H\n#define GENERATED_FLAGS_H\n\n"]
    width = max(len(name) for _bit, name, _doc in definition)
    for bit, name, doc in sorted(definition):
        lines.append("/* %s */\n" % doc)
        lines.append("#define FLAG_%-*s (1u << %d)\n\n" % (width, name, bit))
    lines.append("#define FLAG_COUNT %d\n" % len(definition))
    lines.append("#define FLAG_ALL   0x%xu\n\n"
                 % sum(1 << bit for bit, _n, _d in definition))
    lines.append("#endif\n")
    return "".join(lines)


def sanity(definition):
    """Refuse a definition that cannot be rendered honestly.

    The generator is the last place a contradiction can be caught cheaply;
    after this the bad value is in a header and in everything built from it.
    """
    problems = []
    bits = [b for b, _n, _d in definition]
    names = [n for _b, n, _d in definition]
    if len(set(bits)) != len(bits):
        problems.append("two entries share a bit position")
    if len(set(names)) != len(names):
        problems.append("two entries share a name")
    for bit, name, doc in definition:
        if bit < 0:
            problems.append("%s has a negative bit" % name)
        if not doc:
            problems.append("%s has no meaning written down" % name)
        if not name.isupper():
            problems.append("%s is not upper case" % name)
    return problems


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--write", action="store_true",
                   help="regenerate the derived file")
    g.add_argument("--check", action="store_true",
                   help="fail if the derived file has drifted")
    ap.add_argument("--out", type=pathlib.Path, default=OUTPUT)
    args = ap.parse_args(argv)

    problems = sanity(DEFINITION)
    if problems:
        sys.stderr.write("the definition is inconsistent:\n")
        for p in problems:
            sys.stderr.write("  %s\n" % p)
        return 2

    want = render(DEFINITION)

    if args.write:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(want, encoding="utf-8", newline="\n")
        print("wrote %s (%d entries)" % (args.out, len(DEFINITION)))
        return 0

    if not args.out.is_file():
        sys.stderr.write("%s is missing; run --write\n" % args.out)
        return 1

    have = args.out.read_text(encoding="utf-8")
    if have == want:
        print("%s is exactly what the definition renders (%d entries)"
              % (args.out, len(DEFINITION)))
        return 0

    # Show the drift. A check that says only "differs" sends the reader to
    # guess which half is stale.
    sys.stderr.write("%s has DRIFTED from the definition.\n" % args.out)
    sys.stderr.write("  - committed file   + what the definition renders\n")
    for line in difflib.unified_diff(
            have.splitlines(True), want.splitlines(True),
            fromfile="committed", tofile="definition", n=2):
        sys.stderr.write("  " + line if line.endswith("\n") else "  " + line + "\n")
    sys.stderr.write("\n  Fix by changing the DEFINITION and running --write.\n"
                     "  Editing the generated file is never the fix.\n")
    return 1


if __name__ == "__main__":
    sys.exit(main())
